CREATE TABLE activity_logs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_id       BIGINT                                  NOT NULL,
    performed_by_id BIGINT                                  NOT NULL,
    activity_type   VARCHAR(255)                            NOT NULL,
    details         TEXT,
    timestamp       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_activity_logs PRIMARY KEY (id)
);

CREATE TABLE attachment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name      VARCHAR(255)                            NOT NULL,
    content_type   VARCHAR(100)                            NOT NULL,
    file_size      BIGINT                                  NOT NULL,
    s3_key         VARCHAR(500)                            NOT NULL,
    upload_date    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    report_form_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_attachment PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_id  BIGINT                                  NOT NULL,
    author_id  BIGINT                                  NOT NULL,
    text       TEXT                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE employment_form
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    social_security_number VARCHAR(255)                            NOT NULL,
    first_name             VARCHAR(50),
    last_name              VARCHAR(50),
    email                  VARCHAR(255)                            NOT NULL,
    phone_number           VARCHAR(255),
    role                   VARCHAR(255)                            NOT NULL,
    department             VARCHAR(255)                            NOT NULL,
    status                 VARCHAR(255)                            NOT NULL,
    created_date           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    hr_id                  BIGINT,
    approver_management_id BIGINT,
    CONSTRAINT pk_employmentform PRIMARY KEY (id)
);

CREATE TABLE report_form
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(100),
    description VARCHAR(1000),
    report_date TIMESTAMP WITHOUT TIME ZONE,
    priority    VARCHAR(255)                            NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    issue_type  VARCHAR(255)                            NOT NULL,
    department  VARCHAR(255)                            NOT NULL,
    staff_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_reportform PRIMARY KEY (id)
);

CREATE TABLE staff
(
    employee_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    social_security_number VARCHAR(255)                            NOT NULL,
    first_name             VARCHAR(50),
    last_name              VARCHAR(50),
    email                  VARCHAR(255),
    phone_number           VARCHAR(255),
    role                   VARCHAR(255)                            NOT NULL,
    department             VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_staff PRIMARY KEY (employee_id)
);

CREATE TABLE ticket_attachment
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name VARCHAR(255),
    file_url  VARCHAR(255),
    s3key     VARCHAR(255),
    ticket_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_ticketattachment PRIMARY KEY (id)
);

CREATE TABLE tickets
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255)                            NOT NULL,
    description    TEXT,
    status         VARCHAR(255)                            NOT NULL,
    priority       VARCHAR(255),
    issue_type     VARCHAR(255),
    created_by_id  BIGINT,
    assigned_to_id BIGINT,
    assignee_id    BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tickets PRIMARY KEY (id)
);

ALTER TABLE employment_form
    ADD CONSTRAINT uc_employmentform_email UNIQUE (email);

ALTER TABLE employment_form
    ADD CONSTRAINT uc_employmentform_social_security_number UNIQUE (social_security_number);

ALTER TABLE staff
    ADD CONSTRAINT uc_staff_social_security_number UNIQUE (social_security_number);

ALTER TABLE activity_logs
    ADD CONSTRAINT FK_ACTIVITY_LOGS_ON_PERFORMED_BY FOREIGN KEY (performed_by_id) REFERENCES staff (employee_id);

ALTER TABLE activity_logs
    ADD CONSTRAINT FK_ACTIVITY_LOGS_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

ALTER TABLE attachment
    ADD CONSTRAINT FK_ATTACHMENT_ON_REPORT_FORM FOREIGN KEY (report_form_id) REFERENCES report_form (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES staff (employee_id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

ALTER TABLE employment_form
    ADD CONSTRAINT FK_EMPLOYMENTFORM_ON_APPROVER_MANAGEMENT FOREIGN KEY (approver_management_id) REFERENCES staff (employee_id);

ALTER TABLE employment_form
    ADD CONSTRAINT FK_EMPLOYMENTFORM_ON_HR FOREIGN KEY (hr_id) REFERENCES staff (employee_id);

ALTER TABLE report_form
    ADD CONSTRAINT FK_REPORTFORM_ON_STAFF FOREIGN KEY (staff_id) REFERENCES staff (employee_id);

ALTER TABLE ticket_attachment
    ADD CONSTRAINT FK_TICKETATTACHMENT_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_ASSIGNED_TO FOREIGN KEY (assigned_to_id) REFERENCES staff (employee_id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_ASSIGNEE FOREIGN KEY (assignee_id) REFERENCES staff (employee_id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES staff (employee_id);